package ArchivosEjercicio2;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Fisher
 */
public class MainVentana extends javax.swing.JFrame {

    public MainVentana() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        cajaEdad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cajaPeso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cajaEstatura = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        botonRegistrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        itemVerTabla = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRO ATLETAS");

        panel.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRO");

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 20)); // NOI18N
        jLabel2.setText("NOMBRE: ");

        cajaNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        cajaEdad.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 20)); // NOI18N
        jLabel3.setText("EDAD:");

        cajaPeso.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 20)); // NOI18N
        jLabel4.setText("PESO KG:");

        cajaEstatura.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 20)); // NOI18N
        jLabel5.setText("ESTATURA CM:");

        botonRegistrar.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        botonRegistrar.setText("REGISTRAR ATLETA");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(botonRegistrar)
                        .addGap(248, 248, 248))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cajaEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cajaEstatura, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                                    .addComponent(cajaPeso))))
                        .addGap(27, 27, 27))))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cajaEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cajaPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cajaEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonRegistrar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        menu.setText("MENU");
        menu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        itemVerTabla.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        itemVerTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchivosEjercicio2/Imagenes/atletismo.png"))); // NOI18N
        itemVerTabla.setText("Ver Atletas Registrados");
        itemVerTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerTablaActionPerformed(evt);
            }
        });
        menu.add(itemVerTabla);
        menu.add(jSeparator1);

        itemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchivosEjercicio2/Imagenes/salir.png"))); // NOI18N
        itemSalir.setText("SALIR");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        menu.add(itemSalir);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        System.exit(0); //Se termina el programa cada que se pica en Salir
    }//GEN-LAST:event_itemSalirActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        String nombre;
        int edad, estatura;
        float peso;
        Atleta participante;
        //BLOQUE DE CONTROL DE EXCEPCION POR SI EL USUARIO INGRESA VALORES ERRONEOS
        try {
            nombre = cajaNombre.getText();
            edad = Integer.parseInt(cajaEdad.getText());
            estatura = Integer.parseInt(cajaEstatura.getText());
            peso = Float.parseFloat(cajaPeso.getText());
            participante = new Atleta(nombre, edad, estatura, peso);
            escribirBinario(participante);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ERROR, porfavor, ingrese valores numericos en las casillas correspondientes", 
                    "ERROR DE CONVERSION", 
                    JOptionPane.WARNING_MESSAGE);
        } finally {
            limpiarCajas();
        }
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void itemVerTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerTablaActionPerformed
        ventanaDeAtletasRegistrados ventanaTabla = new ventanaDeAtletasRegistrados(this, true);
        ventanaTabla.setVisible(true); //SE ABRE LA VENTANA DONDE SE VE LOS ATLETAS REGISTRADOS
    }//GEN-LAST:event_itemVerTablaActionPerformed
    
    private void escribirBinario(Atleta participante){
        try {
            //Cada que se llame, se añadira nuevo contenido
            FileOutputStream archivo= new FileOutputStream("C:\\Users\\msi\\Desktop\\ITL\\Cursos de programacion\\Ficheros\\registroAtletas.bin",true);
            //Usaremos la subclase creada a partir de ObjectOutputStream para escribir sobre nuestro fichero
            AñadirBinario escribir = new AñadirBinario(archivo);
            escribir.writeObject(participante);
            escribir.close(); //CERRAMOS EL ARCHIVO CUANDO SE TERMINE DE ESCRIBIR
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "ERROR, LA RUTA DE CREACION DE ARCHIVO NO SE ENCUENTRA", 
                    "ARCHIVO DE REGISTRO NO ENCONTRADO", 
                    JOptionPane.WARNING_MESSAGE);
            System.err.println("ERROR, EL ARCHIVO NO HA SIDO ENCONTRADO "+ex);
        } catch (IOException ex) {
            System.err.println("ERROR, NO SE PUEDE ESCRIBIR SOBRE EL ARCHIVO "+ex);
        }
                
    }
    
    private void limpiarCajas() {
        cajaEstatura.setText("");
        cajaNombre.setText("");
        cajaEdad.setText("");
        cajaPeso.setText("");
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JTextField cajaEdad;
    private javax.swing.JTextField cajaEstatura;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JTextField cajaPeso;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuItem itemVerTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menu;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables

}
